name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        php-versions: ['8.3', '8.4']
        phpunit-versions: ['latest']

    name: PHP ${{ matrix.php-versions }} ${{ matrix.operating-system }}

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress>

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl
          ini-values: post_max_size=256M, max_execution_time=180
          coverage: xdebug
          tools: php-cs-fixer, phpunit:${{ matrix.phpunit-versions }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}